{% set name = "gdsfactory" %}
{% set version = "7.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gdsfactory-{{ version }}.tar.gz
  sha256: d5320b1dadc7a0e6bb5cfc9a56bd189b021f34328a41b8b529502267c9b15a31


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - gf = gdsfactory.gf:gf

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit
  run:
    - typer
    - flatdict
    - gdstk
    - loguru
    - matplotlib-base
    - numpy
    - omegaconf
    - orjson
    - pandas
    - pydantic >=2.0
    - pytest
    - pytest-regressions
    - python >={{ python_min }}
    - pyyaml
    - qrcode
    - rectpack
    - scipy
    - shapely
    - toolz
    - tqdm
    - types-pyyaml
    - typing-extensions
    - watchdog
    - xmltodict
    - rich
    - jinja2

test:
  imports:
    - gdsfactory
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python library to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
