{% set name = "gdsfactory" %}
{% set version = "6.114.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdsfactory-{{ version }}.tar.gz
  sha256: 24b852fa55b2cf88858a72e5ab0b0cf73f18624c5d8840ef9f3bb3d0f4e22cf5


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - gf = gdsfactory.gf:gf

requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - click
    - flatdict
    - gdstk
    - loguru
    - matplotlib-base
    - numpy
    - omegaconf
    - orjson
    - pandas
    - pydantic
    - pytest
    - pytest-regressions
    - python >=3.7
    - pyyaml
    - qrcode
    - rectpack
    - scipy
    - shapely
    - toolz
    - tqdm
    - types-pyyaml
    - typing-extensions
    - watchdog
    - xmltodict
    - rich
    - jinja2

test:
  imports:
    - gdsfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python library to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
